name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

env:
  DIGITALOCEANAPIKEY: ${{ secrets.DIGITALOCEANAPIKEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    
    #steps:
    #- name: Checkout code
      #uses: actions/checkout@v2

    #- name: Set up Node.js
      #uses: actions/setup-node@v2
      #with:
        #node-version: 14

    - name: Install dependencies
      run: |
        npm ci

    - name: Build the application
      run: |
        npm run build

    - name: Deploy to DigitalOcean using Serverless Framework
      run: |
        npx serverless deploy
      env:
        DIGITALOCEANAPIKEY: ${{ env.DIGITALOCEANAPIKEY }}
