env:
  DIGITALOCEANAPIKEY: ${{ secrets.DIGITALOCEANAPIKEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to DigitalOcean
        run: |
          doctl --access-token=${{ env.DIGITALOCEANAPIKEY }} 
