name: Connect to DigitalOcean

on:
  push:
    branches:
      - main

env:
  DIGITALOCEAN: ${{ secrets.DIGITALOCEAN }}

jobs:
  connect:
    runs-on: docker-ubuntu-s-1vcpu-1gb-blr1-01
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to DigitalOcean
      uses: digitalocean/action-doctl@v1
      with:
        api_token: ${{ env.DIGITALOCEAN }}
        command: version
